openapi: 3.0.0
info:
  title: LoginID API 
  description: LoginID documentation 
  version: 1.0.0
  # Contact information: name, email, URL.
  contact:
    name: LoginID Support
    email: support@loginid.io
    url: https://loginid.io
  # Name of the license and a URL to the license description.
  license:
    name: LoginID
    url: https://loginid.io
paths:
  # OpenAPI documents all need a paths element
  /manage/user:
    get:
      summary: Get user information and list of credentials 
      parameters:
        - in: header
          name: Authorization
          description: Authorization token
          required: true
          schema:
            type: string
        - in: query 
          name: username
          description: Username of user to be query
          required: true
          schema:
            type: string
        - in: query
          name: nid
          description: Namespace ID of user organization    

      responses:
        '200':
          description: Return user entity object  
          content:
            application/json:    
              schema:
                type: object
                  properties:
                    id: 
                      type: string
                      example: 2bb131a2-070f-4fd6-9faf-85e9aa993fa0
                    status:
                      type: string
                      example: active
                    created:
                      type: int64
                      example:   12341341412  
                    credentials: array
                      items: 
                        type: object
                        properties: 
                          id:
                            type: string
                            example: 9449b8bb-e7a4-4e76-8d20-1c0c732c6b7f
                          desc:
                            type: string
                            example: Android Samsung s9

